### PR TITLE
Handles missing Forum/Topics

### LINKED ISSUE #1627: Broken URL - Jobs Marketplace
Some links in Jobs Marketplace are giving an Error 500;

image

DEPLOYMENT/Assignment/Secondment EC‑03 or EC 04 Opportunity at the Treasury Board Secretariat / MUTATION/Affectation/Détachement EC 03 ou EC 04 Possibilité au Secrétariat du Conseil du Trésor

https://gcconnex.gc.ca/gcforums/topic/view/32424750

### PR DESCRIPTION
**Pull request by pandurx**

### CODE REVIEW

File: mod/gcforums/start.php [hunk 1]
```diff
@@ -252,162 +263,229 @@ function render_forums($forum_guid) {
...
+							FROM {$dbprefix}entities e, {$dbprefix}users_entity ue
+							WHERE e.container_guid = {$topic->guid} AND e.owner_guid = ue.guid";
+				$replies = get_data($query);
 
-		$content .= "</div> </div> </p> <br/>";
-	}
 
+				$total_replies = count($replies);
+				$topic_starter = get_user($topic->owner_guid)->username;
+				$time_posted = $replies[count($total_replies) - 1]->time_created;
```
Comment (Phanoix) [inline mod/gcforums/start.php]: Isn't $total_replies an int at this point since it's the size of replies? I'm guessing this is supposed to be time created of the last post, so
```php
$replies[$total_replies - 1]->time_created;

File: mod/gcforums/start.php [hunk 2]
```diff
@@ -252,162 +263,229 @@ function render_forums($forum_guid) {
...
+				$time_posted = date('Y-m-d H:i:s', $time_posted);
 
+				$options = render_edit_options($topic->guid, $group_entity->guid);
+				if ($options == '') $options = '-';
+				$admin_only = (elgg_is_admin_logged_in()) ? "(guid:{$topic->guid})" : "";
+				$last_post = ($total_replies <= 0) ? $last_post = elgg_echo('gcforums:no_posts') : "<div>{$replies[$total_replies - 1]->username}</div> <div>{$time_posted}</div>";
```
Comment (Phanoix) [inline mod/gcforums/start.php]: Did you mean:
```php
$last_post = ($total_replies <= 0) ? elgg_echo('gcforums:no_posts') : "<div>{$replies[$total_replies - 1]->username}</div> <div>{$time_posted}</div>";
