### PR TITLE
fixes for 500 error on department news feed

### LINKED ISSUE #1642: Department tab in newsfeed gives 500 error
User reports this is hit or miss. Sometimes clicking on his department tab in the Newsfeed brings a 500 error.

User: sas120
Department: National Defense

Linked to https://github.com/Phanoix/gcconnex-help/issues/41

Was unable to replicate.

### PR DESCRIPTION
**Pull request by Troy-Lawson**
fixes #1642

### CODE REVIEW

File: mod/groups/start.php [hunk 1]
```diff
@@ -1277,7 +1278,7 @@ function discussion_reply_menu_setup($hook, $type, $return, $params) {
 				'confirm' => elgg_echo('deleteconfirm'),
 			));
 		}
-		
+	}
```
Comment (Phanoix) [inline mod/groups/start.php]: you're missing a second } here.

File: mod/wet4/start.php [hunk 2]
```diff
@@ -1005,7 +1006,8 @@ function wet4_elgg_entity_menu_setup($hook, $type, $return, $params)
                     );
                     $return[] = \ElggMenuItem::factory($options);
                     }
-                }
+				}
+			}
```
Comment (Phanoix) [inline mod/wet4/start.php]: I think you added 1 more } than needed here.
