### PR TITLE
quick fix to link to managers profile

### LINKED ISSUE #1117: Opportunities platform - manager link does not link to profile
When looking at an opportunity the manager profile link redirects to newsfeed. There is a space in the profile link url.

### PR DESCRIPTION
**Pull request by piet0024**
On prod the url contains the managers display name and it redirects to newsfeed. Changed the url to link to the profile with username. This should now properly link to the managers profile.

Fixes #1117

### CODE REVIEW

File: mod/missions/views/default/page/elements/mission-manager-info.php [hunk 1]
```diff
@@ -38,7 +38,7 @@
 $manager_icon = elgg_view_entity_icon(get_entity(1), 'small');
 if($manager_account) {
 	$manager_name = elgg_view('output/url', array(
-			'href' => elgg_get_site_url().'profile/'.$manager_name,//$manager_account->getURL(), //Nick changed to profile url
+			'href' => elgg_get_site_url().'profile/'.$manager_account->username,//$manager_account->getURL(), //Nick changed to profile url
```
Comment (nschonni) [inline mod/missions/views/default/page/elements/mission-manager-info.php]: Might be good to clear off the inline comments
